### ISSUE TITLE
No module 'price_transforms'

### ISSUE THREAD

**Issue by pavarotti** [trevormcguire/blog#1]
import numpy as np
import pandas as pd
from typing import Callable
from copy import deepcopy
from price_transforms import features
from price_transforms import transforms
import random
import matplotlib.pyplot as plt

# I am getting the following: (Windows 10, Anaconda Navigator, Jupyter Notebook)
# Any suggestions?

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_648\3795909693.py in <module>
      3 from typing import Callable
      4 from copy import deepcopy
----> 5 from price_transforms import features
      6 from price_transforms import transforms
      7 import random

ModuleNotFoundError: No module named 'price_transforms'

**Comment by trevormcguire** [comment]
Hey @pavarotti , price_transforms is a private repo I have. It contains a bunch of technical analysis calculations. A good open source library for that is talib (https://github.com/mrjbq7/ta-lib)

**Comment by pavarotti** [comment]
Hi Trevor!

Thanks for the heads up!

I am familiar with the talib library and that is what I ended up using.

Your code for Reinforcement Learning is excellent and I have been running
it today.
I am in Sydney Australia and have fed the RL process some of our local
stock market data that I get curated from Norgate.

At the moment I apply scaling via MinMaxScaler and am investigating
Fractional Differencing as well.

Initially, I started with Dr Howard Bandy's Quantitative Technical Analysis
wherein he uses a fairly simple Logistic model and
recommends holding stock for only a maximum of several days.

RL requires a different mindset I am discovering!

I can't quite get my head around how the RL process provides me with a
trade for tomorrow.
The Logistic model gives me a prediction for the next day's trade: Buy,
Sell or Do Nothing but how do I get something similar from RL?

Cheers, Any suggestions appreciated, Peter

**Comment by rsadaphule** [comment]
https://github.com/trevormcguire/blogposts/tree/main/RL/Blackjack.ipypb. Has bunch of errors when I run it locally. The state is supposed to be tuple of 3 values but it returns only 2 values. Here is the error. 
Cell In[15], line 7, in update_qtable(qtable, state, action, reward, next_state, alpha, gamma)
      6 def update_qtable(qtable, state, action, reward, next_state, alpha, gamma):
----> 7     curr_idx1, curr_idx2, curr_idx3 = get_state_idxs(state)
      8     next_idx1, next_idx2, next_idx3 = get_state_idxs(next_state)
      9     curr_state_q = qtable[curr_idx1][curr_idx2][curr_idx3]
Cell In[15], line 2, in get_state_idxs(state)
      1 def get_state_idxs(state):
----> 2     idx1, idx2, idx3 = state
      3     idx3 = int(idx3)
      4     return idx1, idx2, idx3
ValueError: not enough values to unpack (expected 3, got 2). 
 
There is not enough documentation to fix this. How should I proceed?

**Comment by rsadaphule** [comment]
Can you make price_transforms public so that I can run stock notebook in RL folder

**Comment by trevormcguire** [comment]
I will be rewriting this blog post without using the package in question
